name: Deploy docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Copy README and CONTRIBUTING to docs dir
        run: |
          sed 's/docs\///g' README.md > ./docs/README.md
          cp CONTRIBUTING.md ./docs/

      - name: Deploy to GitHub Pages
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CUSTOM_DOMAIN: docs.cog.run
